# Lab 03: Fun with `pandas`!

Below are some exercises to get you working with `pandas` to manipulate data. As always, get as far as you can, and ask for help when you need it! Your teacher (me), you instructor, and your classmates are all here to help each other get better at coding. Getting the code to work is important, but do also take the time to make sure you understand what the commands are doing. This time, (with the exception of the Stroop challenge), all I've given you is the code to download the data. Then you are on your own. For the Stroop challenge, I gave the you code for the first step—after that, it's up to you :-)

## Music sales challenge

Write a script that:

1. Combines the tables of best-selling physical singles and best-selling digital singles on the Wikipedia page "List_of_best-selling_singles"
2. Adds a column which marks whether each row is from the list of physical singles or digital singles
3. Outputs the artist and single name for the year you were born. If there is no entry for that year, take the closest year after you were born.
4. Outputs the artist and single name for the year you were 15 years old.

In [3]:
# Starter code...

#%pip install lxml
import pandas as pd

rawdata = pd.read_html("https://en.wikipedia.org/wiki/List_of_best-selling_singles")

all_tables_preview = pd.concat(rawdata, keys=range(len(rawdata)))
print(all_tables_preview.head(10))

print(f"Number of tables found: {len(rawdata)}")
for i, table in enumerate(rawdata):
    print(f"\nTable {i}:\n")
    print(table.head())

                      Artist  \
0 0              Bing Crosby
  1               Elton John
  2              Bing Crosby
  3               Tino Rossi
  4  Bill Haley & His Comets
  5          Whitney Houston
  6            Elvis Presley
  7           USA for Africa
  8            The Ink Spots
  9              Celine Dion

                                                Single  Released  \
0 0                                  "White Christmas"    1942.0
  1  "Something About the Way You Look Tonight"/"Ca...    1997.0
  2                                     "Silent Night"    1935.0
  3                                  "Petit Papa Noël"    1946.0
  4                            "Rock Around the Clock"    1954.0
  5                           "I Will Always Love You"    1992.0
  6                                "It's Now or Never"    1960.0
  7                                 "We Are the World"    1985.0
  8                                 "If I Didn't Care"    1939.0
  9                              "My Heart Will Go On"    1997.0

        Sales (in millions)  Source Certified sales  Units (in billions)  \
0 0                      50     [1]             NaN                  NaN
  1                      33     [1]             NaN                  NaN
  2                      30     [2]             NaN                  NaN
  3                      30     [3]             NaN                  NaN
  4                      25  [4][5]             NaN                  NaN
  5                      24  [6][7]             NaN                  NaN
  6                      20  [8][9]             NaN                  NaN
  7                      20    [10]             NaN                  NaN
  8  19[disputed – discuss]    [11]             NaN                  NaN
  9                      18    [12]             NaN                  NaN

     Year Sales (in millions)[b] vteLists of best-selling singles  \
0 0   NaN                    NaN                              NaN
  1   NaN                    NaN                              NaN
  2   NaN                    NaN                              NaN
  3   NaN                    NaN                              NaN
  4   NaN                    NaN                              NaN
  5   NaN                    NaN                              NaN
  6   NaN                    NaN                              NaN
  7   NaN                    NaN                              NaN
  8   NaN                    NaN                              NaN
  9   NaN                    NaN                              NaN

    vteLists of best-selling singles.1 vteMusic industry vteMusic industry.1  \
0 0                                NaN               NaN                 NaN
  1                                NaN               NaN                 NaN
  2                                NaN               NaN                 NaN
  3                                NaN               NaN                 NaN
  4                                NaN               NaN                 NaN
  5                                NaN               NaN                 NaN
  6                                NaN               NaN                 NaN
  7                                NaN               NaN                 NaN
  8                                NaN               NaN                 NaN
  9                                NaN               NaN                 NaN

       0    1 vteIFPI Global Year-End Charts vteIFPI Global Year-End Charts.1
0 0  NaN  NaN                            NaN                              NaN
  1  NaN  NaN                            NaN                              NaN
  2  NaN  NaN                            NaN                              NaN
  3  NaN  NaN                            NaN                              NaN
  4  NaN  NaN                            NaN                              NaN
  5  NaN  NaN                            NaN                              NaN
  6  NaN  NaN                            NaN                              NaN
  7  NaN  NaN                            NaN                              NaN
  8  NaN  NaN                            NaN                              NaN
  9  NaN  NaN                            NaN                              NaN
Number of tables found: 14

Table 0:

                    Artist                                             Single  \
0              Bing Crosby                                  "White Christmas"
1               Elton John  "Something About the Way You Look Tonight"/"Ca...
2              Bing Crosby                                     "Silent Night"
3               Tino Rossi                                  "Petit Papa Noël"
4  Bill Haley & His Comets                            "Rock Around the Clock"

   Released Sales (in millions)  Source
0      1942                  50     [1]
1      1997                  33     [1]
2      1935                  30     [2]
3      1946                  30     [3]
4      1954                  25  [4][5]

Table 1:

                Artist                            Single  Released  \
0  The Andrews Sisters           "Bei Mir Bist Du Schön"      1937
1            Scorpions                  "Wind of Change"      1991
2   Prince Nico Mbarga                    "Sweet Mother"      1976
3         Kyu Sakamoto                        "Sukiyaki"      1963
4           Gene Autry  "Rudolph the Red-Nosed Reindeer"      1949

   Sales (in millions) Source
0                 14.0   [17]
1                 14.0   [18]
2                 13.0   [19]
3                 13.0   [20]
4                 12.5   [21]

Table 2:

            Artist                             Single  Released  \
0     Mariah Carey  "All I Want for Christmas Is You"      1994
1       Elton John          "Candle in the Wind 1997"      1997
2          Journey             "Don't Stop Believin'"      1981
3  Michael Jackson                         "Thriller"      1983
4  Michael Jackson                      "Billie Jean"      1983

  Certified sales
0    28.9 Million
1    28.7 Million
2    25.1 Million
3    23.1 Million
4      18 Million

Table 3:

                              Artist                      Single  Released  \
0                         Ed Sheeran              "Shape of You"      2017
1  Luis Fonsi featuring Daddy Yankee                 "Despacito"      2017
2            Rihanna featuring Drake                      "Work"      2016
3      The Chainsmokers and Coldplay  "Something Just Like This"      2017
4                         Ed Sheeran                   "Perfect"      2017

  Sales (in millions)    Source
0             41.5[a]  [48][49]
1             36.1[a]  [48][49]
2             32.5[a]      [50]
3             21.5[a]  [48][49]
4             21.4[a]  [48][49]

Table 4:

                                     Artist               Single  Released  \
0  Robin Thicke featuring T.I. and Pharrell      "Blurred Lines"      2013
1     Maroon 5 featuring Christina Aguilera  "Moves Like Jagger"      2011
2                                     Kesha            "Tik Tok"      2009
3                                 Lady Gaga         "Poker Face"      2008
4                         Pharrell Williams              "Happy"      2013

  Sales (in millions) Source
0             14.8[a]   [63]
1                14.4   [64]
2                  14   [65]
3                  14   [66]
4             13.9[a]   [67]

Table 5:

                            Artist             Single  Released  \
0                       The Weeknd  "Blinding Lights"      2019
1                       The Weeknd  "Save Your Tears"      2020
2  The Kid Laroi and Justin Bieber             "Stay"      2021
3                     Harry Styles        "As It Was"      2022
4                         Dua Lipa       "Levitating"      2020

   Units (in billions)        Source
0                 5.31  [81][82][83]
1                 4.66  [82][83][84]
2                 3.81      [82][83]
3                 3.74      [83][84]
4                 2.99      [82][83]

Table 6:

   Year           Artist                            Single Source
0  1966     Barry Sadler  "The Ballad of the Green Berets"   [85]
1  1968      The Beatles                        "Hey Jude"   [86]
2  1969      The Archies                    "Sugar, Sugar"   [87]
3  1990          Madonna                           "Vogue"   [88]
4  1992  Whitney Houston          "I Will Always Love You"   [89]

Table 7:

   Year         Artist                  Single Sales (in millions)[b] Source
0  2007  Avril Lavigne            "Girlfriend"                    7.3   [91]
1  2008      Lil Wayne              "Lollipop"                    9.1   [92]
2  2009      Lady Gaga            "Poker Face"                    9.8   [71]
3  2010          Kesha               "Tik Tok"                   12.8   [93]
4  2011     Bruno Mars  "Just the Way You Are"                   12.5   [69]

Table 8:

  vteLists of best-selling singles  \
0                     Asia-Pacific
1                           Europe
2                    North America
3                    South America
4                   Related topics

                  vteLists of best-selling singles.1
0                        Australia Japan South Korea
1  Belgium Finland France Germany Italy Netherlan...
2                        Canada Mexico United States
3                                             Brazil
4              By country By girl groups Sheet music

Table 9:

                   vteMusic industry  \
0  Major companies and organizations
1                    Representatives
2                         Publishers
3                      Record labels
4                          Retailers

                                 vteMusic industry.1
0  Representatives AMPROFON ARIA BVMI BPI Music C...
1  AMPROFON ARIA BVMI BPI Music Canada FIMI IFPI ...
2  BMG Rights Management Sony Music Publishing Un...
3  Major: Sony Universal Warner Independent: Conc...
4  Amazon Digital music stores (iTunes Store) Fna...

Table 10:

                 0                                                  1
0  Representatives  AMPROFON ARIA BVMI BPI Music Canada FIMI IFPI ...
1       Publishers  BMG Rights Management Sony Music Publishing Un...
2    Record labels  Major: Sony Universal Warner Independent: Conc...
3        Retailers  Amazon Digital music stores (iTunes Store) Fna...
4       Live music     CTS Eventim Live Nation LiveStyle Ticketmaster

Table 11:

            0                                                  1
0  Production  Arrangement Songwriter Composer Lyricist Condu...

Table 12:

          0                                                  1
0  Channels  Channel V CMT Fuse Mnet MTV MTV2 Tr3s MuchMusi...
1    Series  Idol franchise Popstars Star Academy The Four ...

Table 13:

  vteIFPI Global Year-End Charts  \
0             Artist of the Year
1              Album of the Year
2             Single of the Year

                    vteIFPI Global Year-End Charts.1
0  One Direction (2013) Taylor Swift (2014) Adele...
1  Hybrid Theory by Linkin Park (2001) The Eminem...
2  "Girlfriend" by Avril Lavigne (2007) "Lollipop...

In [ ]:
physical_singles = pd.concat([rawdata[0],rawdata[1]])
digital_singles = pd.concat([rawdata[3], rawdata[4], rawdata[5]])

physical_singles['Type'] = 'Physical'
digital_singles['Type'] = 'Digital'

all_singles = pd.concat([physical_singles, digital_singles])

print(all_singles.head(100))

                             Artist  \
0                       Bing Crosby
1                        Elton John
2                       Bing Crosby
3                        Tino Rossi
4           Bill Haley & His Comets
..                              ...
29                    Justin Bieber
30                     Lukas Graham
31     Ed Sheeran and Justin Bieber
32     Lady Gaga and Bradley Cooper
33  The Chainsmokers featuring Daya

                                               Single  Released  \
0                                   "White Christmas"      1942
1   "Something About the Way You Look Tonight"/"Ca...      1997
2                                      "Silent Night"      1935
3                                   "Petit Papa Noël"      1946
4                             "Rock Around the Clock"      1954
..                                                ...       ...
29                                            "Sorry"      2015
30                                          "7 Years"      2015
31                                     "I Don't Care"      2019
32                                          "Shallow"      2018
33                                "Don't Let Me Down"      2016

   Sales (in millions)  Source      Type  Units (in billions)
0                   50     [1]  Physical                  NaN
1                   33     [1]  Physical                  NaN
2                   30     [2]  Physical                  NaN
3                   30     [3]  Physical                  NaN
4                   25  [4][5]  Physical                  NaN
..                 ...     ...       ...                  ...
29             10.8[a]    [52]   Digital                  NaN
30             10.4[a]    [52]   Digital                  NaN
31             10.3[a]    [56]   Digital                  NaN
32             10.2[a]    [56]   Digital                  NaN
33             10.2[a]    [52]   Digital                  NaN

[100 rows x 7 columns]
Empty DataFrame
Columns: [Artist, Single, Released, Sales (in millions), Source, Type, Units (in billions)]
Index: []
                                 Artist                    Single  Released  \
5    Wiz Khalifa featuring Charlie Puth           "See You Again"      2015
8      Mark Ronson featuring Bruno Mars             "Uptown Funk"      2015
10                           Ed Sheeran       "Thinking Out Loud"      2015
5                              Maroon 5                   "Sugar"      2015
10  Major Lazer & DJ Snake featuring MØ                 "Lean On"      2015
12                       Ellie Goulding     "Love Me like You Do"      2015
15                                Adele                   "Hello"      2015
22                        Justin Bieber           "Love Yourself"      2015
29                        Justin Bieber                   "Sorry"      2015
30                         Lukas Graham                 "7 Years"      2015
36                          Mike Posner  "I Took a Pill in Ibiza"      2015

   Sales (in millions) Source     Type  Units (in billions)
5              20.9[a]   [51]  Digital                  NaN
8                20[a]   [51]  Digital                  NaN
10             19.5[a]   [51]  Digital                  NaN
5              13.5[a]   [51]  Digital                  NaN
10             13.1[a]   [51]  Digital                  NaN
12             12.6[a]   [51]  Digital                  NaN
15             12.3[a]   [51]  Digital                  NaN
22             11.7[a]   [52]  Digital                  NaN
29             10.8[a]   [52]  Digital                  NaN
30             10.4[a]   [52]  Digital                  NaN
36               10[a]   [52]  Digital                  NaN

In [8]:

birth_year=2000
age_15_year=2015

birth_single = all_singles[all_singles['Released'] == birth_year]
age15_single = all_singles[all_singles['Released'] == age_15_year]

print(birth_single)
print(age15_single)

Empty DataFrame
Columns: [Artist, Single, Released, Sales (in millions), Source, Type, Units (in billions)]
Index: []
                                 Artist                    Single  Released  \
5    Wiz Khalifa featuring Charlie Puth           "See You Again"      2015
8      Mark Ronson featuring Bruno Mars             "Uptown Funk"      2015
10                           Ed Sheeran       "Thinking Out Loud"      2015
5                              Maroon 5                   "Sugar"      2015
10  Major Lazer & DJ Snake featuring MØ                 "Lean On"      2015
12                       Ellie Goulding     "Love Me like You Do"      2015
15                                Adele                   "Hello"      2015
22                        Justin Bieber           "Love Yourself"      2015
29                        Justin Bieber                   "Sorry"      2015
30                         Lukas Graham                 "7 Years"      2015
36                          Mike Posner  "I Took a Pill in Ibiza"      2015

   Sales (in millions) Source     Type  Units (in billions)
5              20.9[a]   [51]  Digital                  NaN
8                20[a]   [51]  Digital                  NaN
10             19.5[a]   [51]  Digital                  NaN
5              13.5[a]   [51]  Digital                  NaN
10             13.1[a]   [51]  Digital                  NaN
12             12.6[a]   [51]  Digital                  NaN
15             12.3[a]   [51]  Digital                  NaN
22             11.7[a]   [52]  Digital                  NaN
29             10.8[a]   [52]  Digital                  NaN
30             10.4[a]   [52]  Digital                  NaN
36               10[a]   [52]  Digital                  NaN

## Space challenge

1. Make a single dataframe that combines the space missions from the 1950's to the 2020's
2. Write a script that returns the year with the most launches
3. Write a script that returns the most common month for launches
4. Write a script that ranks the months from most launches to fewest launches

In [18]:
import pandas as pd

rawdata = pd.read_html("https://en.wikipedia.org/wiki/Timeline_of_Solar_System_exploration")

all_tables_preview = pd.concat(rawdata, keys=range(len(rawdata)))
print(all_tables_preview.head(10))

print(f"Number of tables found: {len(rawdata)}")
for i, table in enumerate(rawdata):
    print(f"\nTable {i}:\n")
    print(table.head())

    Mission name        Launch date  \
0 0    Sputnik 1     4 October 1957
  1    Sputnik 2    3 November 1957
  2   Explorer 1    1 February 1958
  3   Vanguard 1      17 March 1958
  4       Luna 1     2 January 1959
  5    Pioneer 4       3 March 1959
  6       Luna 2  12 September 1959
  7       Luna 3     4 October 1959
1 0    Pioneer 5      11 March 1960
  1     Venera 1   12 February 1961

                                           Description         Ref(s)  \
0 0                                First Earth orbiter         [1][2]
  1  Earth orbiter, first animal in orbit, a dog na...      [2][3][4]
  2  Earth orbiter; discovered Van Allen radiation ...            [5]
  3  Earth orbiter; oldest spacecraft still in Eart...            [6]
  4  First lunar flyby (attempted lunar impact?); f...  [7][8][9][10]
  5                                        Lunar flyby       [11][12]
  6  First extraterrestrial impact and lunar impact...       [10][13]
  7  Lunar flyby; First images of another celestial...       [10][14]
1 0                Interplanetary space investigations       [15][16]
  1  First probe to another planet; Venus flyby (co...   [17][18][19]

    vteSpaceflight lists and timelines vteSpaceflight lists and timelines.1  \
0 0                                NaN                                  NaN
  1                                NaN                                  NaN
  2                                NaN                                  NaN
  3                                NaN                                  NaN
  4                                NaN                                  NaN
  5                                NaN                                  NaN
  6                                NaN                                  NaN
  7                                NaN                                  NaN
1 0                                NaN                                  NaN
  1                                NaN                                  NaN

       0    1 vteExploration of the Solar System  \
0 0  NaN  NaN                                NaN
  1  NaN  NaN                                NaN
  2  NaN  NaN                                NaN
  3  NaN  NaN                                NaN
  4  NaN  NaN                                NaN
  5  NaN  NaN                                NaN
  6  NaN  NaN                                NaN
  7  NaN  NaN                                NaN
1 0  NaN  NaN                                NaN
  1  NaN  NaN                                NaN

    vteExploration of the Solar System.1  \
0 0                                  NaN
  1                                  NaN
  2                                  NaN
  3                                  NaN
  4                                  NaN
  5                                  NaN
  6                                  NaN
  7                                  NaN
1 0                                  NaN
  1                                  NaN

    vteNASA planetary exploration programs  \
0 0                                    NaN
  1                                    NaN
  2                                    NaN
  3                                    NaN
  4                                    NaN
  5                                    NaN
  6                                    NaN
  7                                    NaN
1 0                                    NaN
  1                                    NaN

    vteNASA planetary exploration programs.1 vteSolar System vteSolar System.1
0 0                                      NaN             NaN               NaN
  1                                      NaN             NaN               NaN
  2                                      NaN             NaN               NaN
  3                                      NaN             NaN               NaN
  4                                      NaN             NaN               NaN
  5                                      NaN             NaN               NaN
  6                                      NaN             NaN               NaN
  7                                      NaN             NaN               NaN
1 0                                      NaN             NaN               NaN
  1                                      NaN             NaN               NaN
Number of tables found: 18

Table 0:

  Mission name      Launch date  \
0    Sputnik 1   4 October 1957
1    Sputnik 2  3 November 1957
2   Explorer 1  1 February 1958
3   Vanguard 1    17 March 1958
4       Luna 1   2 January 1959

                                         Description         Ref(s)
0                                First Earth orbiter         [1][2]
1  Earth orbiter, first animal in orbit, a dog na...      [2][3][4]
2  Earth orbiter; discovered Van Allen radiation ...            [5]
3  Earth orbiter; oldest spacecraft still in Eart...            [6]
4  First lunar flyby (attempted lunar impact?); f...  [7][8][9][10]

Table 1:

  Mission name       Launch date  \
0    Pioneer 5     11 March 1960
1     Venera 1  12 February 1961
2     Vostok 1     12 April 1961
3     Ranger 1    23 August 1961
4     Ranger 2  18 November 1961

                                         Description        Ref(s)
0                Interplanetary space investigations      [15][16]
1  First probe to another planet; Venus flyby (co...  [17][18][19]
2          First crewed Earth orbiter (Yuri Gagarin)      [20][21]
3  Attempted lunar test flight (failed to leave E...  [22][23][24]
4  Attempted lunar test flight (failed to leave E...  [24][25][26]

Table 2:

         Mission name        Launch date  \
0           Apollo 13      11 April 1970
1            Venera 7     17 August 1970
2             Luna 16  12 September 1970
3              Zond 8    20 October 1970
4  Luna 17/Lunokhod 1   10 November 1970

                                         Description                Ref(s)
0  Crewed lunar flyby and return to Earth (crewed...  [157][158][159][160]
1  First Venus lander and the first spacecraft to...        [18][161][162]
2                  First robotic lunar sample return             [10][163]
3                    Lunar flyby and return to Earth        [46][164][165]
4                      First remote controlled rover             [10][166]

Table 3:

  Mission name       Launch date  \
0    Venera 13   30 October 1981
1    Venera 14   4 November 1981
2    Venera 15       2 June 1983
3    Venera 16       7 June 1983
4       Vega 1  15 December 1984

                                         Description  \
0  Venus flyby and lander. First recording of sou...
1                             Venus flyby and lander
2                                      Venus orbiter
3                                      Venus orbiter
4  Venus flyby, lander and first extraterrestrial...

                      Ref(s)
0        [18][257][258][259]
1        [18][260][261][262]
2             [18][263][264]
3             [18][265][266]
4  [267][268][269][270][271]

Table 4:

             Mission name        Launch date  \
0         Hiten (MUSES-A)    24 January 1990
1  Hubble Space Telescope      24 April 1990
2                 Ulysses     6 October 1990
3        Yohkoh (Solar-A)     30 August 1991
4           Mars Observer  25 September 1992

                                         Description           Ref(s)
0                            Lunar flyby and orbiter       [296][297]
1  Orbital space telescope (operational since 199...  [298][299][300]
2                                Solar polar orbiter  [301][302][303]
3                     Solar observations (1991–2001)       [304][305]
4              Attempted Mars orbiter (contact lost)       [306][307]

Table 5:

            Mission name    Launch date  \
0      2001 Mars Odyssey   7 April 2001
1                Genesis  8 August 2001
2                CONTOUR    3 July 2002
3     Hayabusa (MUSES-C)     9 May 2003
4  Mars Express/Beagle 2    2 June 2003

                                         Description                Ref(s)
0                                       Mars orbiter            [349][350]
1                     First solar wind sample return  [351][352][353][354]
2  Attempted flyby of comet nuclei (Encke, Schwas...            [355][356]
3  Asteroid lander and first sample return from a...       [357][358][359]
4     Mars orbiter/attempted lander (lander failure)  [360][361][362][363]

Table 6:

                 Mission name       Launch date  \
0  Solar Dynamics Observatory  11 February 2010
1         Akatsuki (Planet-C)       20 May 2010
2                      PICARD      15 June 2010
3                   Chang'e 2    1 October 2010
4                        Juno     5 August 2011

                                         Description           Ref(s)
0                        Continuous solar monitoring       [418][419]
1  Venus orbiter (orbit insertion failed in 2010 ...  [420][421][422]
2                                   Solar monitoring       [423][424]
3        Lunar orbiter, asteroid 4179 Toutatis flyby  [405][425][426]
4                                    Jupiter orbiter       [427][428]

Table 7:

                                        Mission name       Launch date  \
0                                      Solar Orbiter  10 February 2020
1                                          Mars Hope      19 July 2020
2                          Tianwen-1 (Zhurong rover)      23 July 2020
3  Mars 2020 (Perseverance rover and Ingenuity he...      30 July 2020
4                                          Chang'e 5  23 November 2020

                                         Description           Ref(s)
0                            Sun-observing satellite  [474][475][476]
1                                       Mars orbiter            [477]
2                    Mars orbiter, lander, and rover            [478]
3  Mars rover and helicopter drone; first powered...  [479][480][481]
4                                Lunar sample return       [405][482]

Table 8:

  vteSpaceflight lists and timelines  \
0            Timeline of spaceflight
1                            General
2                  Human spaceflight
3                            General
4                             Salyut

                vteSpaceflight lists and timelines.1
0                            Timeline of spaceflight
1  Space exploration outline timeline Spacecraft ...
2  General Crewed spacecraft timeline by program ...
3  Crewed spacecraft timeline by program Spacefli...
4  Expeditions Spaceflights crewed uncrewed Space...

Table 9:

          0                                                  1
0   General  Crewed spacecraft timeline by program Spacefli...
1    Salyut  Expeditions Spaceflights crewed uncrewed Space...
2       Mir  Expeditions ESA Spaceflights crewed uncrewed S...
3       ISS  Expeditions ESA Visiting Spaceflights crewed u...
4  Tiangong         Expeditions Crewed Spaceflights Spacewalks

Table 10:

     vteExploration of the Solar System  \
0  Timeline of Solar System exploration
1                        Exploration of
2                    Artificial objects
3         On extra-terrestrial surfaces
4                   Deep-space missions

                vteExploration of the Solar System.1
0               Timeline of Solar System exploration
1  Mercury Venus Moon Mars Jupiter Saturn Uranus ...
2  On extra-terrestrial surfaces Moon Venus Mars ...
3                              Moon Venus Mars Titan
4        Heliocentric orbit Leaving the Solar System

Table 11:

                               0                                            1
0  On extra-terrestrial surfaces                        Moon Venus Mars Titan
1            Deep-space missions  Heliocentric orbit Leaving the Solar System

Table 12:

              vteNASA planetary exploration programs  \
0                                             Active
1  Large strategic science missions Lunar Discove...
2                                          Completed
3                                          Cancelled
4                              List of NASA missions

            vteNASA planetary exploration programs.1
0  Large strategic science missions Lunar Discove...
1  Large strategic science missions Lunar Discove...
2  Lunar Orbiter Lunar Precursor Mariner MESUR Ne...
3  Grand Tour Mariner Mark II Project Prometheus ...
4                              List of NASA missions

Table 13:

                                                   0  \
0  Large strategic science missions Lunar Discove...

                                                   1
0  Large strategic science missions Lunar Discove...

Table 14:

                                     vteSolar System  \
0  Sun Mercury Venus Earth Mars Ceres Jupiter Sat...
1  Planets,  dwarfs, minors Terrestrials Mercury ...
2  Planets,  dwarfs, minors Terrestrials Mercury ...
3                           Planets,  dwarfs, minors
4                                              Moons

                                   vteSolar System.1
0  Sun Mercury Venus Earth Mars Ceres Jupiter Sat...
1  Planets,  dwarfs, minors Terrestrials Mercury ...
2  Rings Earth? Jovian Saturnian (Rhean?) Charikl...
3  Terrestrials Mercury Venus Earth Mars Giants G...
4  Earth Moon Claimed Mars Phobos Deimos Jupiter ...

Table 15:

                                                   0  \
0  Planets,  dwarfs, minors Terrestrials Mercury ...
1                           Planets,  dwarfs, minors
2                                              Moons
3        Formation, evolution, contents, and History
4                                              Rings

                                                   1
0  Rings Earth? Jovian Saturnian (Rhean?) Charikl...
1  Terrestrials Mercury Venus Earth Mars Giants G...
2  Earth Moon Claimed Mars Phobos Deimos Jupiter ...
3  Star formation Accretion Accretion disk Excret...
4  Earth? Jovian Saturnian (Rhean?) Charikloan Ch...

Table 16:

                                             0  \
0                     Planets,  dwarfs, minors
1                                        Moons
2  Formation, evolution, contents, and History

                                                   1
0  Terrestrials Mercury Venus Earth Mars Giants G...
1  Earth Moon Claimed Mars Phobos Deimos Jupiter ...
2  Star formation Accretion Accretion disk Excret...

Table 17:

                           0  \
0                      Rings
1       Hypothetical objects
2      Exploration (outline)
3  Small Solar System bodies
4                      Lists

                                                   1
0  Earth? Jovian Saturnian (Rhean?) Charikloan Ch...
1  Bagby's moon Chiron Coatlicue Counter-Earth Ch...
2  Colonization Discovery astronomy historical mo...
3  Comets Damocloids Meteoroids Minor planets nam...
4  Comets Possible dwarf planets Gravitationally ...

In [21]:
space_data = pd.concat([rawdata[0], rawdata[1], rawdata[2], rawdata[3], rawdata[4], rawdata[5], rawdata[6], rawdata[7],rawdata[8]], ignore_index=True)
space_data['Launch date'] = pd.to_datetime(space_data['Launch date'], errors='coerce')
space_data['Month'] = space_data['Launch date'].dt.month
space_data['Year'] = space_data['Launch date'].dt.year
most_launches_year = space_data['Year'].value_counts().idxmax()
most_common_month = space_data['Month'].value_counts().idxmax()
month_ranking = space_data['Month'].value_counts().sort_values(ascending=False)

print("Year with most launches:", most_launches_year)
print("Most common month:", most_common_month)
print("Month rankings:\n", month_ranking)

Year with most launches: 1965.0
Most common month: 11.0
Month rankings:
 Month
11.0    30
8.0     27
10.0    24
9.0     22
7.0     21
1.0     19
12.0    19
5.0     17
3.0     15
2.0     14
6.0     14
4.0     13
Name: count, dtype: int64

## Supervillain challenge

1. Write a script that combines the tables showing supervillain debuts from the 30's through the 2010's
2. Write a script that ranks each decade in terms of how many supervillains debuted in that decade
3. Write a script that ranks the different comics companies in terms of how many supervillains they have, and display the results in a nice table (pandas dataframe)

In [22]:
rawdata = pd.read_html("https://en.wikipedia.org/wiki/List_of_comic_book_supervillain_debuts")

all_tables_preview = pd.concat(rawdata, keys=range(len(rawdata)))
print(all_tables_preview.head(10))

print(f"Number of tables found: {len(rawdata)}")
for i, table in enumerate(rawdata):
    print(f"\nTable {i}:\n")
    print(table.head())

      0                                                  1 Character / Team  \
0 0 NaN  This article has multiple issues. Please help ...              NaN
  1 NaN  This article includes a list of general refere...              NaN
  2 NaN  This article needs additional citations for ve...              NaN
1 0 NaN  This article includes a list of general refere...              NaN
2 0 NaN  This article needs additional citations for ve...              NaN
3 0 NaN                                                NaN   Ultra-Humanite
  1 NaN                                                NaN        Dr. Death
  2 NaN                                                NaN         The Monk
  3 NaN                                                NaN         The Claw
4 0 NaN                                                NaN         Hath-Set

         Year Debuted                   Company                    Creator/s  \
0 0               NaN                       NaN                          NaN
  1               NaN                       NaN                          NaN
  2               NaN                       NaN                          NaN
1 0               NaN                       NaN                          NaN
2 0               NaN                       NaN                          NaN
3 0       1939 (June)                        DC    Jerry Siegel, Joe Shuster
  1       1939 (July)                        DC        Bob Kane, Bill Finger
  2  1939 (September)                        DC        Bob Kane, Bill Finger
  3   1939 (December)  Lev Gleason Publications                    Jack Cole
4 0    1940 (January)                        DC  Gardner Fox, Dennis Neville

                  First Appearance
0 0                            NaN
  1                            NaN
  2                            NaN
1 0                            NaN
2 0                            NaN
3 0     Action Comics (vol. 1) #13
  1  Detective Comics (vol. 1) #29
  2  Detective Comics (vol. 1) #31
  3        Silver Streak Comics #1
4 0                Flash Comics #1
Number of tables found: 12

Table 0:

    0                                                  1
0 NaN  This article has multiple issues. Please help ...
1 NaN  This article includes a list of general refere...
2 NaN  This article needs additional citations for ve...

Table 1:

    0                                                  1
0 NaN  This article includes a list of general refere...

Table 2:

    0                                                  1
0 NaN  This article needs additional citations for ve...

Table 3:

  Character / Team      Year Debuted                   Company  \
0   Ultra-Humanite       1939 (June)                        DC
1        Dr. Death       1939 (July)                        DC
2         The Monk  1939 (September)                        DC
3         The Claw   1939 (December)  Lev Gleason Publications

                   Creator/s               First Appearance
0  Jerry Siegel, Joe Shuster     Action Comics (vol. 1) #13
1      Bob Kane, Bill Finger  Detective Comics (vol. 1) #29
2      Bob Kane, Bill Finger  Detective Comics (vol. 1) #31
3                  Jack Cole        Silver Streak Comics #1

Table 4:

         Character / Team     Year Debuted            Company  \
0                Hath-Set   1940 (January)                 DC
1  Professor Hugo Strange  1940 (February)                 DC
2           Doctor Sivana  1940 (February)  Fawcett Comics/DC
3              Lex Luthor     1940 (April)                 DC
4               The Joker     1940 (April)                 DC

                               Creator/s               First Appearance
0            Gardner Fox, Dennis Neville                Flash Comics #1
1                  Bob Kane, Bill Finger  Detective Comics (vol. 1) #36
2                Bill Parker, C. C. Beck                 Whiz Comics #2
3              Jerry Siegel, Joe Shuster     Action Comics (vol. 1) #23
4  Bob Kane, Jerry Robinson, Bill Finger             Batman (vol. 1) #1

Table 5:

  Character / Team     Year Debuted Company  \
0         Deadshot      1950 (June)      DC
1        The Mekon             1950     NaN
2         Red Hood  1951 (February)      DC
3      Killer Moth  1951 (February)      DC
4          Firefly      1952 (June)      DC

                                 Creator/s               First Appearance
0  Bob Kane, David Vern Reed, Lew Schwartz            Batman (vol. 1) #59
1                            Frank Hampson  Dan Dare, Pilot of the Future
2                                      NaN          Detective Comics #168
3                                      NaN                     Batman #63
4               France Herron, Dick Sprang          Detective Comics #184

Table 6:

  Character / Team     Year Debuted Company                       Creator/s  \
0           Grottu  1960 (February)  Marvel        Jack Kirby, Bill Everett
1           Starro  1960 (February)      DC                     Gardner Fox
2            Amazo      1960 (June)      DC                     Gardner Fox
3    Professor Ivo      1960 (June)      DC      Gardner Fox, Mike Sekowsky
4        Trickster      1960 (June)      DC  John Broome, Carmine Infantino

                      First Appearance
0                    Strange Tales #73
1  The Brave and the Bold (vol. 1) #28
2  The Brave and the Bold (vol. 1) #30
3  The Brave and the Bold (vol. 1) #30
4              The Flash (vol. 1) #113

Table 7:

          Character / Team    Year Debuted Company  \
0          Agatha Harkness  1970 (January)  Marvel
1                    Arkon    1970 (April)  Marvel
2                  Man-Bat     1970 (June)      DC
3            Lethal Legion     1970 (July)  Marvel
4  Intergang (Morgan Edge)  1970 (October)      DC

                              Creator/s                 First Appearance
0                  Stan Lee, Jack Kirby               Fantastic Four #94
1              Roy Thomas, John Buscema                     Avengers #75
2             Frank Robbins, Neal Adams   Detective Comics (vol. 1) #400
3  Roy Thomas, John Buscema, Tom Palmer                     Avengers #78
4                            Jack Kirby  Superman's Pal Jimmy Olsen #133

Table 8:

  Character / Team Year Debuted Company  \
0        Cutthroat         1980  Marvel
1          Destiny         1980  Marvel
2   Sebastian Shaw         1980  Marvel
3   Rainbow Raider         1980      DC
4   Dansen Macabre         1980  Marvel

                                     Creator/s          First Appearance
0                                          NaN  Marvel Team-Up Vol.1 #89
1                  Chris Claremont, John Byrne        Uncanny X-Men #141
2                  Chris Claremont, John Byrne        Uncanny X-Men #131
3                                   Cary Bates                Flash #286
4  Steven Grant, Tom Sutton, Carmine Infantino  Marvel Team-Up vol.1 #93

Table 9:

                 Character / Team Year Debuted Company  \
0                      Crimesmith         1990      DC
1                        NKVDemon         1990      DC
2                     Blackout #2  1990 (June)  Marvel
3  Cyborg Superman (Hank Henshaw)         1990      DC
4                       Yuga Khan         1990      DC

                 Creator/s             First Appearance
0             Marv Wolfman                  Batman #443
1  Marv Wolfman, Jim Aparo                  Batman #445
2            Howard Mackie               Ghost Rider #2
3              Dan Jurgens  Adventures of Superman #466
4                      NaN          New Gods Vol.2, #17

Table 10:

  Character / Team Year Debuted Company                    Creator/s  \
0       Kyle Abbot         2000      DC                   Greg Rucka
1       Able Crown         2000      DC                          NaN
2         Agamemno         2000      DC                          NaN
3             Orca         2000      DC                   Larry Hama
4            Zeiss         2000      DC  Ed Brubaker, Scott McDaniel

        First Appearance
0  Detective Comics #743
1  Detective Comics #744
2          Silver Age #1
3            Batman #579
4            Batman #582

Table 11:

       Character / Team      Year Debuted          Company  \
0        Allegra Garcia   2010 (December)               DC
1          Tommy Merlyn  2012 (September)               DC
2  Gorr the God Butcher    2013 (January)           Marvel
3             Robo-Chef              2013  Disney/Hyperion
4             Bloodwork     2016 (August)               DC

                                           Creator/s  \
0  Eric Wallace, Fabrizio Florentinom, Cliff Rich...
1                                   Brian Buccellato
2                                        Jason Aaron
3                                      Rhode Montijo
4                                   Brian Buccellato

                                    First Appearance
0                                         Titans #28
1                             Green Arrow (vol.5) #0
2                            Thor: God of Thunder #1
3  The Gumazing Gum Girl! Book 1: Chews Your Destiny
4                                      The Flash #28

In [24]:
supervillain_data = pd.concat([rawdata[3], rawdata[4], rawdata[5], rawdata[6], rawdata[7], rawdata[8], rawdata[9], rawdata[10],rawdata[11]], ignore_index=True)

supervillain_data['Year Debuted'] = supervillain_data['Year Debuted'].str.extract(r'(\d{4})').astype(int)
supervillain_data['Decade'] = (supervillain_data['Year Debuted'] // 10) * 10
decade_ranking = supervillain_data['Decade'].value_counts()

company_ranking = supervillain_data['Company'].value_counts()

print("Decade rankings:\n", decade_ranking)
print("Company rankings:\n", company_ranking)

Decade rankings:
 Decade
1960    228
1970     97
1980     92
1990     84
2000     49
1940     47
1950     26
2010      9
1930      4
Name: count, dtype: int64
Company rankings:
 Company
DC                          338
Marvel                      264
Fawcett Comics/DC             6
Image                         5
Dark Horse                    5
Marvel/Timely                 4
Disney/Hyperion               4
Eternity                      3
Lev Gleason Publications      1
Comico                        1
Mirage                        1
Image Comics                  1
Name: count, dtype: int64

## Stroop challenge

Every year between 2015 and 2021, the students in my Language, Cognition, and the Brain course participated in a version of the Stroop task. Using a stopwatch (ok, using their phones), they recorded how fast they could say a list of things (either reading or naming colors or color words). The column names mean "Reading with No Interference", "Naming with Interference", "Naming with No Interference", and "Reading with Interference". The times are in seconds.

### Stroop challenge 1: 
Transform these data from wide format to long format, so that the result is a dataframe with
- 1 column named "Participant_id" with a unique number for each participant (you can use the row indices)
- 1 column named "Year" with the year data
- 1 column named "Task" that shows which task they were doing
- 1 column named "RT" that shows their response time

In [36]:
# Starter code 1...

df = pd.read_csv("https://raw.githubusercontent.com/ethanweed/Stroop/master/Stroop-raw-over-the-years.csv")
df.head()

   Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0           4.16        6.76          4.45         4.65  2015
1           4.35        7.73          4.78         4.46  2015
2           3.60        7.00          4.00         3.50  2015
3           3.90        9.03          4.60         6.30  2015
4           4.22        9.98          6.83         6.24  2015

In [37]:
df.index.name = 'Participant_id'
df.reset_index(inplace=True)

long_df = pd.melt(
    df,
    id_vars=['Participant_id', 'Year'],
    var_name='Task',
    value_name='RT'
)

print(long_df.head(190))
#Not sure how to show this in a way that is pretty in python, but by manually finding when a task would first show up i could double check that it worked as intended.

     Participant_id  Year           Task     RT
0                 0  2015  Reading_NoInt   4.16
1                 1  2015  Reading_NoInt   4.35
2                 2  2015  Reading_NoInt   3.60
3                 3  2015  Reading_NoInt   3.90
4                 4  2015  Reading_NoInt   4.22
..              ...   ...            ...    ...
185               3  2015     Naming_Int   9.03
186               4  2015     Naming_Int   9.98
187               5  2015     Naming_Int   6.51
188               6  2015     Naming_Int  11.57
189               7  2015     Naming_Int   7.33

[190 rows x 4 columns]

In [154]:
# Starter code 2...

# Make a new column using the dataframe indices as particpant numbers

df.index.name = 'Participant_id'
df = df.reset_index()

#df.reset_index(inplace = True)
# NOTE: This line does exactly the same thing as the line above:
# it replaces the original df with a new df with the updated index. That's what
# "inplace = True" means. Or, you can just assign the dataframe with the updated index
# to a new dataframe with the same name as the old dataframe, which is what I did above.
# The end result is the same.

df

,Participant_id,Reading_NoInt,Naming_Int,Naming_NoInt,Reading_Int,Year
0,0,4.16,6.76,4.45,4.65,2015
1,1,4.35,7.73,4.78,4.46,2015
2,2,3.60,7.00,4.00,3.50,2015
3,3,3.90,9.03,4.60,6.30,2015
4,4,4.22,9.98,6.83,6.24,2015
...,...,...,...,...,...,...
177,177,4.30,7.08,6.25,4.28,2021
178,178,4.75,9.66,6.12,5.49,2021
179,179,4.98,7.52,6.73,5.16,2021
180,180,5.16,8.81,8.19,5.51,2021
181,181,4.27,10.40,5.32,4.59,2021

## Stroop challenge 2 (Advanced!!!):

Make a new dataframe which shows the mean response time (in seconds) for each task for each year.